[package]
name = "kbpwrd"
version = "0.1.0"
edition = "2021"

[profile.release]
opt-level = 3
lto = true

[dependencies]
tokio = { version = "1", features = ["rt", "fs", "time", "macros"] }
serde = "1"
serde_derive = "1"
anyhow = "1"
log = "0.4"
env_logger = "0.9"
